# Generated by Django 2.0.3 on 2018-03-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='art_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AddField(
            model_name='product',
            name='auchan_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena Auchan'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='mediaexpert_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena Media Expert'),
        ),
        migrations.AddField(
            model_name='product',
            name='mediaexpert_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link do Media Expert'),
        ),
        migrations.AddField(
            model_name='product',
            name='mediamarkt_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena Media Markt'),
        ),
        migrations.AddField(
            model_name='product',
            name='mediamarkt_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link do Media Markt'),
        ),
        migrations.AddField(
            model_name='product',
            name='plu_num',
            field=models.IntegerField(default=0, verbose_name='Numer krótki'),
        ),
        migrations.AddField(
            model_name='product',
            name='rtveuro_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Cena RTVEuroAGD'),
        ),
        migrations.AddField(
            model_name='product',
            name='rtveuro_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link do RTVEuroAGD'),
        ),
    ]
