# Generated by Django 2.0.3 on 2018-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_product_auchan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nazwa artykułu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='auchan_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nazwa Auchan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mediaexpert_url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Link do Media Expert'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mediamarkt_url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Link do Media Markt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='plu_num',
            field=models.IntegerField(default=0, unique=True, verbose_name='Numer krótki'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rtveuro_url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Link do RTVEuroAGD'),
        ),
    ]
