# Generated by Django 2.0.3 on 2018-04-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20180402_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mediaexpert_url_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='mediamarkt_url_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rtveuro_url_valid',
            field=models.BooleanField(default=False),
        ),
    ]
